# Generated by Django 6.0.1 on 2026-02-06 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ProductImage', models.ImageField(upload_to='products')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.categorydb')),
            ],
        ),
    ]
