# Generated by Django 6.0.1 on 2026-02-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0003_alter_productdb_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='serviceDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceName', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('ServiceImage', models.ImageField(upload_to='services')),
            ],
        ),
    ]
