# Generated by Django 6.0.1 on 2026-02-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0004_servicedb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrationdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('confrimpassword', models.CharField(max_length=100)),
            ],
        ),
    ]
