# Generated by Django 6.0.1 on 2026-02-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0002_cartdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='productimage',
            field=models.ImageField(blank=True, null=True, upload_to='cart_images'),
        ),
    ]
