# Generated by Django 6.0.1 on 2026-02-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0003_alter_cartdb_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='price',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cartdb',
            name='total_price',
            field=models.IntegerField(max_length=100),
        ),
    ]
