# Generated by Django 6.0.1 on 2026-02-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0005_chechoutdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='chechoutdb',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
