# Generated by Django 6.0.1 on 2026-02-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0006_chechoutdb_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chechoutdb',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
